export default [
  {
    id: 1,
    element: "deck1",
    name: "Eidolon of the Great Revel",
    manaCost: "{R}{R}",
    cmc: 2,
    colors: ["Red"],
    types: ["Creature"],
    text:
      "Whenever a player casts a spell with converted mana cost 3 or less, Eidolon of the Great Revel deals 2 damage to that player.",
    abilities: [],
    power: 2,
    toughness: 2,
    imgUrl: "https://www.mtgpics.com/pics/big/25m/128.jpg",
    backImgUrl: "https://i.ebayimg.com/images/g/l9YAAOSweW5VX2or/s-l300.jpg",
  },
  {
    id: 2,
    element: "deck1",
    name: "Eidolon of the Great Revel",
    manaCost: "{R}{R}",
    cmc: 2,
    colors: ["Red"],
    types: ["Creature"],
    text:
      "Whenever a player casts a spell with converted mana cost 3 or less, Eidolon of the Great Revel deals 2 damage to that player.",
    abilities: [],
    power: 2,
    toughness: 2,
    imgUrl: "https://www.mtgpics.com/pics/big/25m/128.jpg",
    backImgUrl: "https://i.ebayimg.com/images/g/l9YAAOSweW5VX2or/s-l300.jpg",
  },
  {
    id: 3,
    element: "deck1",
    name: "Eidolon of the Great Revel",
    manaCost: "{R}{R}",
    cmc: 2,
    colors: ["Red"],
    types: ["Creature"],
    text:
      "Whenever a player casts a spell with converted mana cost 3 or less, Eidolon of the Great Revel deals 2 damage to that player.",
    abilities: [],
    power: 2,
    toughness: 2,
    imgUrl: "https://www.mtgpics.com/pics/big/25m/128.jpg",
    backImgUrl: "https://i.ebayimg.com/images/g/l9YAAOSweW5VX2or/s-l300.jpg",
  },
  {
    id: 4,
    element: "deck1",
    name: "Eidolon of the Great Revel",
    manaCost: "{R}{R}",
    cmc: 2,
    colors: ["Red"],
    types: ["Creature"],
    text:
      "Whenever a player casts a spell with converted mana cost 3 or less, Eidolon of the Great Revel deals 2 damage to that player.",
    abilities: [],
    power: 2,
    toughness: 2,
    imgUrl: "https://www.mtgpics.com/pics/big/25m/128.jpg",
    backImgUrl: "https://i.ebayimg.com/images/g/l9YAAOSweW5VX2or/s-l300.jpg",
  },
  {
    id: 5,
    element: "deck1",
    name: "Goblin Guide",
    manaCost: "{R}",
    cmc: 1,
    colors: ["Red"],
    types: ["Creature"],
    text:
      "Whenever Goblin Guide attacks, defending player reveals the top card of their library. If it's a land card, that player puts it into their hand.",
    abilities: ["Haste"],
    power: 2,
    toughness: 2,
    imgUrl: "https://www.mtgpics.com/pics/big/zen/126.jpg",
    backImgUrl: "https://i.ebayimg.com/images/g/l9YAAOSweW5VX2or/s-l300.jpg",
  },
  {
    id: 6,
    element: "deck1",
    name: "Goblin Guide",
    manaCost: "{R}",
    cmc: 1,
    colors: ["Red"],
    types: ["Creature"],
    text:
      "Whenever Goblin Guide attacks, defending player reveals the top card of their library. If it's a land card, that player puts it into their hand.",
    abilities: ["Haste"],
    power: 2,
    toughness: 2,
    imgUrl: "https://www.mtgpics.com/pics/big/zen/126.jpg",
    backImgUrl: "https://i.ebayimg.com/images/g/l9YAAOSweW5VX2or/s-l300.jpg",
  },
  {
    id: 7,
    element: "deck1",
    name: "Goblin Guide",
    manaCost: "{R}",
    cmc: 1,
    colors: ["Red"],
    types: ["Creature"],
    text:
      "Whenever Goblin Guide attacks, defending player reveals the top card of their library. If it's a land card, that player puts it into their hand.",
    abilities: ["Haste"],
    power: 2,
    toughness: 2,
    imgUrl: "https://www.mtgpics.com/pics/big/zen/126.jpg",
    backImgUrl: "https://i.ebayimg.com/images/g/l9YAAOSweW5VX2or/s-l300.jpg",
  },
  {
    id: 8,
    element: "deck1",
    name: "Goblin Guide",
    manaCost: "{R}",
    cmc: 1,
    colors: ["Red"],
    types: ["Creature"],
    text:
      "Whenever Goblin Guide attacks, defending player reveals the top card of their library. If it's a land card, that player puts it into their hand.",
    abilities: ["Haste"],
    power: 2,
    toughness: 2,
    imgUrl: "https://www.mtgpics.com/pics/big/zen/126.jpg",
    backImgUrl: "https://i.ebayimg.com/images/g/l9YAAOSweW5VX2or/s-l300.jpg",
  },
  {
    id: 9,
    element: "deck1",
    name: "Monastery Swiftspear",
    manaCost: "{R}",
    cmc: 1,
    colors: ["Red"],
    types: ["Creature"],
    text:
      "Whenever Goblin Guide attacks, defending player reveals the top card of their library. If it's a land card, that player puts it into their hand.",
    abilities: ["Haste", "Prowess"],
    power: 1,
    toughness: 2,
    imgUrl: "https://www.mtgpics.com/pics/big/ima/140.jpg",
    backImgUrl: "https://i.ebayimg.com/images/g/l9YAAOSweW5VX2or/s-l300.jpg",
  },
  {
    id: 10,
    element: "deck1",
    name: "Monastery Swiftspear",
    manaCost: "{R}",
    cmc: 1,
    colors: ["Red"],
    types: ["Creature"],
    text:
      "Whenever Goblin Guide attacks, defending player reveals the top card of their library. If it's a land card, that player puts it into their hand.",
    abilities: ["Haste", "Prowess"],
    power: 1,
    toughness: 2,
    imgUrl: "https://www.mtgpics.com/pics/big/ima/140.jpg",
    backImgUrl: "https://i.ebayimg.com/images/g/l9YAAOSweW5VX2or/s-l300.jpg",
  },
  {
    id: 11,
    element: "deck1",
    name: "Monastery Swiftspear",
    manaCost: "{R}",
    cmc: 1,
    colors: ["Red"],
    types: ["Creature"],
    text:
      "Whenever Goblin Guide attacks, defending player reveals the top card of their library. If it's a land card, that player puts it into their hand.",
    abilities: ["Haste", "Prowess"],
    power: 1,
    toughness: 2,
    imgUrl: "https://www.mtgpics.com/pics/big/ima/140.jpg",
    backImgUrl: "https://i.ebayimg.com/images/g/l9YAAOSweW5VX2or/s-l300.jpg",
  },
  {
    id: 12,
    element: "deck1",
    name: "Monastery Swiftspear",
    manaCost: "{R}",
    cmc: 1,
    colors: ["Red"],
    types: ["Creature"],
    text:
      "Whenever Goblin Guide attacks, defending player reveals the top card of their library. If it's a land card, that player puts it into their hand.",
    abilities: ["Haste", "Prowess"],
    power: 1,
    toughness: 2,
    imgUrl: "https://www.mtgpics.com/pics/big/ima/140.jpg",
    backImgUrl: "https://i.ebayimg.com/images/g/l9YAAOSweW5VX2or/s-l300.jpg",
  },
  {
    id: 1,
    element: "deck2",
    name: "Eidolon of the Great Revel",
    manaCost: "{R}{R}",
    cmc: 2,
    colors: ["Red"],
    types: ["Creature"],
    text:
      "Whenever a player casts a spell with converted mana cost 3 or less, Eidolon of the Great Revel deals 2 damage to that player.",
    abilities: [],
    power: 2,
    toughness: 2,
    imgUrl: "https://www.mtgpics.com/pics/big/25m/128.jpg",
    backImgUrl: "https://i.ebayimg.com/images/g/l9YAAOSweW5VX2or/s-l300.jpg",
  },
  {
    id: 2,
    element: "deck2",
    name: "Eidolon of the Great Revel",
    manaCost: "{R}{R}",
    cmc: 2,
    colors: ["Red"],
    types: ["Creature"],
    text:
      "Whenever a player casts a spell with converted mana cost 3 or less, Eidolon of the Great Revel deals 2 damage to that player.",
    abilities: [],
    power: 2,
    toughness: 2,
    imgUrl: "https://www.mtgpics.com/pics/big/25m/128.jpg",
    backImgUrl: "https://i.ebayimg.com/images/g/l9YAAOSweW5VX2or/s-l300.jpg",
  },
  {
    id: 3,
    element: "deck2",
    name: "Eidolon of the Great Revel",
    manaCost: "{R}{R}",
    cmc: 2,
    colors: ["Red"],
    types: ["Creature"],
    text:
      "Whenever a player casts a spell with converted mana cost 3 or less, Eidolon of the Great Revel deals 2 damage to that player.",
    abilities: [],
    power: 2,
    toughness: 2,
    imgUrl: "https://www.mtgpics.com/pics/big/25m/128.jpg",
    backImgUrl: "https://i.ebayimg.com/images/g/l9YAAOSweW5VX2or/s-l300.jpg",
  },
  {
    id: 4,
    element: "deck2",
    name: "Eidolon of the Great Revel",
    manaCost: "{R}{R}",
    cmc: 2,
    colors: ["Red"],
    types: ["Creature"],
    text:
      "Whenever a player casts a spell with converted mana cost 3 or less, Eidolon of the Great Revel deals 2 damage to that player.",
    abilities: [],
    power: 2,
    toughness: 2,
    imgUrl: "https://www.mtgpics.com/pics/big/25m/128.jpg",
    backImgUrl: "https://i.ebayimg.com/images/g/l9YAAOSweW5VX2or/s-l300.jpg",
  },
  {
    id: 5,
    element: "deck2",
    name: "Goblin Guide",
    manaCost: "{R}",
    cmc: 1,
    colors: ["Red"],
    types: ["Creature"],
    text:
      "Whenever Goblin Guide attacks, defending player reveals the top card of their library. If it's a land card, that player puts it into their hand.",
    abilities: ["Haste"],
    power: 2,
    toughness: 2,
    imgUrl: "https://www.mtgpics.com/pics/big/zen/126.jpg",
    backImgUrl: "https://i.ebayimg.com/images/g/l9YAAOSweW5VX2or/s-l300.jpg",
  },
  {
    id: 6,
    element: "deck2",
    name: "Goblin Guide",
    manaCost: "{R}",
    cmc: 1,
    colors: ["Red"],
    types: ["Creature"],
    text:
      "Whenever Goblin Guide attacks, defending player reveals the top card of their library. If it's a land card, that player puts it into their hand.",
    abilities: ["Haste"],
    power: 2,
    toughness: 2,
    imgUrl: "https://www.mtgpics.com/pics/big/zen/126.jpg",
    backImgUrl: "https://i.ebayimg.com/images/g/l9YAAOSweW5VX2or/s-l300.jpg",
  },
  {
    id: 7,
    element: "deck2",
    name: "Goblin Guide",
    manaCost: "{R}",
    cmc: 1,
    colors: ["Red"],
    types: ["Creature"],
    text:
      "Whenever Goblin Guide attacks, defending player reveals the top card of their library. If it's a land card, that player puts it into their hand.",
    abilities: ["Haste"],
    power: 2,
    toughness: 2,
    imgUrl: "https://www.mtgpics.com/pics/big/zen/126.jpg",
    backImgUrl: "https://i.ebayimg.com/images/g/l9YAAOSweW5VX2or/s-l300.jpg",
  },
  {
    id: 8,
    element: "deck2",
    name: "Goblin Guide",
    manaCost: "{R}",
    cmc: 1,
    colors: ["Red"],
    types: ["Creature"],
    text:
      "Whenever Goblin Guide attacks, defending player reveals the top card of their library. If it's a land card, that player puts it into their hand.",
    abilities: ["Haste"],
    power: 2,
    toughness: 2,
    imgUrl: "https://www.mtgpics.com/pics/big/zen/126.jpg",
    backImgUrl: "https://i.ebayimg.com/images/g/l9YAAOSweW5VX2or/s-l300.jpg",
  },
  {
    id: 9,
    element: "deck2",
    name: "Monastery Swiftspear",
    manaCost: "{R}",
    cmc: 1,
    colors: ["Red"],
    types: ["Creature"],
    text:
      "Whenever Goblin Guide attacks, defending player reveals the top card of their library. If it's a land card, that player puts it into their hand.",
    abilities: ["Haste", "Prowess"],
    power: 1,
    toughness: 2,
    imgUrl: "https://www.mtgpics.com/pics/big/ima/140.jpg",
    backImgUrl: "https://i.ebayimg.com/images/g/l9YAAOSweW5VX2or/s-l300.jpg",
  },
  {
    id: 10,
    element: "deck2",
    name: "Monastery Swiftspear",
    manaCost: "{R}",
    cmc: 1,
    colors: ["Red"],
    types: ["Creature"],
    text:
      "Whenever Goblin Guide attacks, defending player reveals the top card of their library. If it's a land card, that player puts it into their hand.",
    abilities: ["Haste", "Prowess"],
    power: 1,
    toughness: 2,
    imgUrl: "https://www.mtgpics.com/pics/big/ima/140.jpg",
    backImgUrl: "https://i.ebayimg.com/images/g/l9YAAOSweW5VX2or/s-l300.jpg",
  },
  {
    id: 11,
    element: "deck2",
    name: "Monastery Swiftspear",
    manaCost: "{R}",
    cmc: 1,
    colors: ["Red"],
    types: ["Creature"],
    text:
      "Whenever Goblin Guide attacks, defending player reveals the top card of their library. If it's a land card, that player puts it into their hand.",
    abilities: ["Haste", "Prowess"],
    power: 1,
    toughness: 2,
    imgUrl: "https://www.mtgpics.com/pics/big/ima/140.jpg",
    backImgUrl: "https://i.ebayimg.com/images/g/l9YAAOSweW5VX2or/s-l300.jpg",
  },
  {
    id: 12,
    element: "deck2",
    name: "Monastery Swiftspear",
    manaCost: "{R}",
    cmc: 1,
    colors: ["Red"],
    types: ["Creature"],
    text:
      "Whenever Goblin Guide attacks, defending player reveals the top card of their library. If it's a land card, that player puts it into their hand.",
    abilities: ["Haste", "Prowess"],
    power: 1,
    toughness: 2,
    imgUrl: "https://www.mtgpics.com/pics/big/ima/140.jpg",
    backImgUrl: "https://i.ebayimg.com/images/g/l9YAAOSweW5VX2or/s-l300.jpg",
  },
  {
    id: 13,
    element: "deck3",
    name: "Eidolon of the Great Revel",
    manaCost: "{R}{R}",
    cmc: 2,
    colors: ["Red"],
    types: ["Creature"],
    text:
      "Whenever a player casts a spell with converted mana cost 3 or less, Eidolon of the Great Revel deals 2 damage to that player.",
    abilities: [],
    power: 2,
    toughness: 2,
    imgUrl: "https://www.mtgpics.com/pics/big/25m/128.jpg",
    backImgUrl: "https://i.ebayimg.com/images/g/l9YAAOSweW5VX2or/s-l300.jpg",
  },
  {
    id: 14,
    element: "deck3",
    name: "Eidolon of the Great Revel",
    manaCost: "{R}{R}",
    cmc: 2,
    colors: ["Red"],
    types: ["Creature"],
    text:
      "Whenever a player casts a spell with converted mana cost 3 or less, Eidolon of the Great Revel deals 2 damage to that player.",
    abilities: [],
    power: 2,
    toughness: 2,
    imgUrl: "https://www.mtgpics.com/pics/big/25m/128.jpg",
    backImgUrl: "https://i.ebayimg.com/images/g/l9YAAOSweW5VX2or/s-l300.jpg",
  },
  {
    id: 15,
    element: "deck3",
    name: "Eidolon of the Great Revel",
    manaCost: "{R}{R}",
    cmc: 2,
    colors: ["Red"],
    types: ["Creature"],
    text:
      "Whenever a player casts a spell with converted mana cost 3 or less, Eidolon of the Great Revel deals 2 damage to that player.",
    abilities: [],
    power: 2,
    toughness: 2,
    imgUrl: "https://www.mtgpics.com/pics/big/25m/128.jpg",
    backImgUrl: "https://i.ebayimg.com/images/g/l9YAAOSweW5VX2or/s-l300.jpg",
  },
  {
    id: 16,
    element: "deck3",
    name: "Eidolon of the Great Revel",
    manaCost: "{R}{R}",
    cmc: 2,
    colors: ["Red"],
    types: ["Creature"],
    text:
      "Whenever a player casts a spell with converted mana cost 3 or less, Eidolon of the Great Revel deals 2 damage to that player.",
    abilities: [],
    power: 2,
    toughness: 2,
    imgUrl: "https://www.mtgpics.com/pics/big/25m/128.jpg",
    backImgUrl: "https://i.ebayimg.com/images/g/l9YAAOSweW5VX2or/s-l300.jpg",
  },
  {
    id: 17,
    element: "deck3",
    name: "Goblin Guide",
    manaCost: "{R}",
    cmc: 1,
    colors: ["Red"],
    types: ["Creature"],
    text:
      "Whenever Goblin Guide attacks, defending player reveals the top card of their library. If it's a land card, that player puts it into their hand.",
    abilities: ["Haste"],
    power: 2,
    toughness: 2,
    imgUrl: "https://www.mtgpics.com/pics/big/zen/126.jpg",
    backImgUrl: "https://i.ebayimg.com/images/g/l9YAAOSweW5VX2or/s-l300.jpg",
  },
  {
    id: 18,
    element: "deck3",
    name: "Goblin Guide",
    manaCost: "{R}",
    cmc: 1,
    colors: ["Red"],
    types: ["Creature"],
    text:
      "Whenever Goblin Guide attacks, defending player reveals the top card of their library. If it's a land card, that player puts it into their hand.",
    abilities: ["Haste"],
    power: 2,
    toughness: 2,
    imgUrl: "https://www.mtgpics.com/pics/big/zen/126.jpg",
    backImgUrl: "https://i.ebayimg.com/images/g/l9YAAOSweW5VX2or/s-l300.jpg",
  },
  {
    id: 19,
    element: "deck3",
    name: "Goblin Guide",
    manaCost: "{R}",
    cmc: 1,
    colors: ["Red"],
    types: ["Creature"],
    text:
      "Whenever Goblin Guide attacks, defending player reveals the top card of their library. If it's a land card, that player puts it into their hand.",
    abilities: ["Haste"],
    power: 2,
    toughness: 2,
    imgUrl: "https://www.mtgpics.com/pics/big/zen/126.jpg",
    backImgUrl: "https://i.ebayimg.com/images/g/l9YAAOSweW5VX2or/s-l300.jpg",
  },
  {
    id: 20,
    element: "deck3",
    name: "Goblin Guide",
    manaCost: "{R}",
    cmc: 1,
    colors: ["Red"],
    types: ["Creature"],
    text:
      "Whenever Goblin Guide attacks, defending player reveals the top card of their library. If it's a land card, that player puts it into their hand.",
    abilities: ["Haste"],
    power: 2,
    toughness: 2,
    imgUrl: "https://www.mtgpics.com/pics/big/zen/126.jpg",
    backImgUrl: "https://i.ebayimg.com/images/g/l9YAAOSweW5VX2or/s-l300.jpg",
  },
  {
    id: 21,
    element: "deck3",
    name: "Monastery Swiftspear",
    manaCost: "{R}",
    cmc: 1,
    colors: ["Red"],
    types: ["Creature"],
    text:
      "Whenever Goblin Guide attacks, defending player reveals the top card of their library. If it's a land card, that player puts it into their hand.",
    abilities: ["Haste", "Prowess"],
    power: 1,
    toughness: 2,
    imgUrl: "https://www.mtgpics.com/pics/big/ima/140.jpg",
    backImgUrl: "https://i.ebayimg.com/images/g/l9YAAOSweW5VX2or/s-l300.jpg",
  },
  {
    id: 22,
    element: "deck3",
    name: "Monastery Swiftspear",
    manaCost: "{R}",
    cmc: 1,
    colors: ["Red"],
    types: ["Creature"],
    text:
      "Whenever Goblin Guide attacks, defending player reveals the top card of their library. If it's a land card, that player puts it into their hand.",
    abilities: ["Haste", "Prowess"],
    power: 1,
    toughness: 2,
    imgUrl: "https://www.mtgpics.com/pics/big/ima/140.jpg",
    backImgUrl: "https://i.ebayimg.com/images/g/l9YAAOSweW5VX2or/s-l300.jpg",
  },
  {
    id: 23,
    element: "deck3",
    name: "Monastery Swiftspear",
    manaCost: "{R}",
    cmc: 1,
    colors: ["Red"],
    types: ["Creature"],
    text:
      "Whenever Goblin Guide attacks, defending player reveals the top card of their library. If it's a land card, that player puts it into their hand.",
    abilities: ["Haste", "Prowess"],
    power: 1,
    toughness: 2,
    imgUrl: "https://www.mtgpics.com/pics/big/ima/140.jpg",
    backImgUrl: "https://i.ebayimg.com/images/g/l9YAAOSweW5VX2or/s-l300.jpg",
  },
  {
    id: 24,
    element: "deck3",
    name: "Monastery Swiftspear",
    manaCost: "{R}",
    cmc: 1,
    colors: ["Red"],
    types: ["Creature"],
    text:
      "Whenever Goblin Guide attacks, defending player reveals the top card of their library. If it's a land card, that player puts it into their hand.",
    abilities: ["Haste", "Prowess"],
    power: 1,
    toughness: 2,
    imgUrl: "https://www.mtgpics.com/pics/big/ima/140.jpg",
    backImgUrl: "https://i.ebayimg.com/images/g/l9YAAOSweW5VX2or/s-l300.jpg",
  },
];
